# Stunnel configuration for off services
# /usr/share/doc/stunnel4/examples/stunnel.conf-sample

# we need this to run it smoothly with systemd
foreground = yes
# drop root
setuid = stunnel4
setgid = stunnel4

pid = /var/run/stunnel-off/stunnel.pid
# Can be emerg, alert, crit, err, warning, notice, info or debug
debug = err

# stunnel client is for client = yes service, the other should go to reverse-proxy

[OffPostgres]
client = yes
accept = 5432
connect = 213.36.253.214:5432
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/postgres-psk.txt

[OffRedis]
client = yes
accept = 6379
connect = 213.36.253.214:6379
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/redis-psk.txt

# Triton deployed on gpu-01
# Open Prices deployed on scaleway server need to access
# Triton
[Triton-HTTP]
client = yes
accept = 10.13.1.101:5505
connect = 34.140.15.35:5506
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt

[Triton-gRPC]
client = yes
accept = 10.13.1.101:5504
connect = 34.140.15.35:5507
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/triton-psk.txt
