# Stunnel configuration for off services
# /usr/share/doc/stunnel4/examples/stunnel.conf-sample

# we need this to run it smoothly with systemd
foreground = yes
# drop root
setuid = stunnel4
setgid = stunnel4
pid = /tmp/stunnel.pid
debug = warning

# enabling connections to PaddleX
[Paddlex]
client = no
accept = 10.12.1.113:5610
connect = 10.12.1.201:5610
ciphers = PSK
PSKsecrets = /etc/stunnel/psk/paddlex-psk.txt
